// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6kHAplTASMBXm53Hgbj4IH-gt_Tcr690',
    appId: '1:225929117670:web:7dc93c41da19260af2a027',
    messagingSenderId: '225929117670',
    projectId: 'agua-41cd1',
    authDomain: 'agua-41cd1.firebaseapp.com',
    storageBucket: 'agua-41cd1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC04Laob1j3UbZn_NLBNoD2KMs4KpS3RbE',
    appId: '1:225929117670:android:837b68f2a1742263f2a027',
    messagingSenderId: '225929117670',
    projectId: 'agua-41cd1',
    storageBucket: 'agua-41cd1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6kHAplTASMBXm53Hgbj4IH-gt_Tcr690',
    appId: '1:225929117670:web:83f518e70e429aaff2a027',
    messagingSenderId: '225929117670',
    projectId: 'agua-41cd1',
    authDomain: 'agua-41cd1.firebaseapp.com',
    storageBucket: 'agua-41cd1.firebasestorage.app',
  );
}
